import { esc,money } from './core.js?v=2026091903';
const SALES_PHONE = '0352 978 519';
const SALES_ADVISOR = 'Bùi Đắc Thịnh';
const feeRow = (label, value, note = "") => `<div><span>${esc(label)}${note ? `<small>${esc(note)}</small>` : ""}</span><b>${money(value)}</b></div>`;
const feeDivider = label => `<div class="fee-divider"><span>${esc(label)}</span></div>`;
const feeSubtotal = (label, value) => `<div class="fee-subtotal"><span>${esc(label)}</span><b>${money(value)}</b></div>`;
const formatPercentage = value => new Intl.NumberFormat("vi-VN",{ maximumFractionDigits:1 }).format(value);


export function renderQuoteForm(quoteCars,promotions) { return `<section class="quote-hero"><span>CÔNG CỤ BÁO GIÁ</span><h1>Lập báo giá VinFast.</h1><p>Chọn xe, phiên bản, màu sắc và thông tin đăng ký để xem ngay chi phí dự kiến theo hai phương thức thanh toán.</p></section>
    <section class="quote-workspace"><form class="quote-form" id="quote-form">
      <div class="quote-form__heading"><span>THÔNG TIN BÁO GIÁ</span><h2>Lựa chọn của khách hàng</h2></div>
      <div class="customer-fields"><label><span>Tên khách hàng <small>Không bắt buộc</small></span><input id="customer-name" type="text" placeholder="Nhập tên khách hàng"></label><label><span>Số điện thoại <small>Không bắt buộc</small></span><input id="customer-phone" type="tel" placeholder="Nhập số điện thoại"></label></div>
      <fieldset><legend>Xe và phiên bản</legend><div class="form-grid"><label><span>Dòng xe · xếp theo giá tăng dần</span><select id="car-select">${quoteCars.map(car => `<option value="${car.slug}">${esc(car.name)}</option>`).join("")}</select></label><label><span>Phiên bản</span><select id="version-select"></select></label></div><label><span>Màu ngoại thất</span><select id="color-select"></select></label></fieldset>
      <fieldset><legend>Ưu đãi áp dụng</legend><div class="quote-promotion-group"><span>Ưu đãi theo dòng xe</span><div class="promotion-options" id="model-promotions"></div></div><label><span>Ưu đãi theo khách hàng</span><select id="customer-promotion"><option value="">Không áp dụng</option>${promotions.quoteOptions.customer.map(item => `<option value="${esc(item.id)}">${esc(item.label)}</option>`).join("")}</select></label><p class="promotion-help">${esc(promotions.futureGreen2.quoteNote)}</p><label><span>Giảm giá thêm <small>Có thể bỏ trống</small></span><div class="money-input"><input id="discount" type="text" inputmode="numeric" placeholder="0" aria-describedby="discount-limit discount-note"><i>₫</i></div><small class="field-guidance" id="discount-limit"></small><small class="field-validation" id="discount-note" role="status" aria-live="polite"></small></label></fieldset>
      <fieldset><legend>Đăng ký và sử dụng</legend><div class="choice-group"><span>Khu vực đăng ký biển</span><div><label><input type="radio" name="registration" value="province" checked><b>Tỉnh</b><small>140.000 ₫</small></label><label><input type="radio" name="registration" value="city"><b>Thành phố</b><small>14.000.000 ₫</small></label></div></div><div class="choice-group"><span>Loại biển số</span><div><label><input type="radio" name="plate" value="white" checked><b>Biển trắng</b><small>Xe cá nhân</small></label><label><input type="radio" name="plate" value="yellow"><b>Biển vàng</b><small>Xe kinh doanh</small></label></div></div><div class="choice-group is-three"><span>Phí dịch vụ đăng ký xe</span><div><label><input type="radio" name="registrationService" value="0"><b>Miễn phí</b><small>0 ₫</small></label><label><input type="radio" name="registrationService" value="3000000" checked><b>3 triệu</b><small>Mặc định</small></label><label><input type="radio" name="registrationService" value="5000000"><b>5 triệu</b><small>Gói dịch vụ</small></label></div></div><label class="check-option"><input id="physical-cash" type="checkbox"><span><b>Thêm bảo hiểm vật chất cho thanh toán tiền mặt</b><small>Không bắt buộc khi mua tiền mặt. Phương án vay luôn bắt buộc.</small></span></label></fieldset>
      <fieldset class="loan-quote-options" id="loan-quote-options" hidden><legend>Phương án trả góp</legend><div class="loan-percentage-presets"><span>Chọn tỷ lệ vay</span><div role="group" aria-label="Chọn tỷ lệ vay"><button type="button" data-loan-percentage="75" aria-pressed="false"><b>Vay 75%</b><small>Trả trước 25%</small></button><button type="button" data-loan-percentage="80" aria-pressed="false"><b>Vay 80%</b><small>Trả trước 20%</small></button><button type="button" data-loan-percentage="85" aria-pressed="true"><b>Vay 85%</b><small>Trả trước 15%</small></button></div></div><label><span>Số tiền trả trước <small>Có thể nhập số tiền khác</small></span><div class="money-input"><input id="loan-down-payment" type="text" inputmode="numeric" aria-describedby="loan-down-payment-note"><i>₫</i></div></label><div class="loan-default-control"><small id="loan-down-payment-note" aria-live="polite"></small></div></fieldset>
    </form><aside class="quote-results" id="quote-results"></aside></section>`; }
export function renderQuoteResults(state) {
const {car,version,color,customer,customerPhone,listPrice,pendingColorPrice,colorFee,modelPromotions,customerPromotion,customerDiscount,customerPromotionNote,manualDiscount,vehicleValue,paymentMode,cashTotal,loanTotal,registration,registrationType,registrationService,road,plate,liability,liabilityNote,physical,physicalInsurance,cashRollingCosts,loanRollingCosts,downPayment,downPaymentPercentageText,loanPercentageText,remainingLoan,physicalCash,inspection} = state;
return `<div class="quote-result-head"><div><span>BÁO GIÁ DỰ KIẾN</span><h2>${esc(car.name)}</h2><p>${esc(version.name)} · ${esc(color)}</p>${customer ? `<small>Khách hàng: ${esc(customer)}${customerPhone ? ` · ${esc(customerPhone)}` : ""}</small>` : customerPhone ? `<small>SĐT khách hàng: ${esc(customerPhone)}</small>` : ""}<a class="quote-contact" href="tel:0352978519"><span>Tư vấn bán hàng</span><b>${SALES_ADVISOR}</b><small>${SALES_PHONE}</small></a></div><div class="quote-actions"><button class="is-secondary" type="button" id="download-quote-image">Tải ảnh báo giá</button><small id="quote-export-status" role="status" aria-live="polite"></small></div></div>
      <section class="vehicle-cost"><h3>Giá trị xe</h3>${feeRow("Giá niêm yết",listPrice)}${pendingColorPrice ? '<div><span>Phụ phí màu</span><b>Chưa công bố</b></div>' : feeRow("Phụ phí màu",colorFee)}${modelPromotions.filter(item => item.type === "fixed").map(item => feeRow("Ưu đãi dòng xe",-item.value,item.label)).join("")}${modelPromotions.filter(item => item.type === "gift").map(item => `<div class="promotion-gift"><span>${esc(item.label)}<small>${esc(item.note || "Quà tặng kèm")}</small></span><b>Tặng kèm</b></div>`).join("")}${customerPromotion ? feeRow("Ưu đãi khách hàng",-customerDiscount,customerPromotionNote) : ""}${manualDiscount ? feeRow("Giảm giá thêm",-manualDiscount) : ""}<div class="subtotal"><span>Giá xe sau ưu đãi</span><b>${money(vehicleValue)}</b></div></section>
      <div class="payment-switch" role="tablist" aria-label="Phương thức thanh toán"><button type="button" role="tab" data-payment-mode="cash" aria-selected="${paymentMode === "cash"}">Trả thẳng</button><button type="button" role="tab" data-payment-mode="loan" aria-selected="${paymentMode === "loan"}">Trả góp</button></div>
      <div class="payment-results"><article class="payment-card cash" data-payment-panel="cash" ${paymentMode === "cash" ? "" : "hidden"}><span>THANH TOÁN TIỀN MẶT</span><h3>${money(cashTotal)}</h3><p>Giá xe cộng tổng chi phí lăn bánh và bảo hiểm tùy chọn.</p><div class="fee-breakdown">${feeRow("Giá xe",vehicleValue)}${feeDivider("Chi phí lăn bánh")}${feeRow("Đăng ký biển",registration,registrationType === "city" ? "Thành phố" : "Tỉnh")}${feeRow("Phí dịch vụ đăng ký xe",registrationService)}${feeRow("Lệ phí đăng kiểm",inspection)}${feeRow("Bảo trì đường bộ",road,plate === "white" ? "Biển trắng" : "Biển vàng")}${feeRow("Bảo hiểm TNDS",liability,liabilityNote)}${physicalCash ? feeRow("Bảo hiểm vật chất",physical,physicalInsurance.note) : ""}${feeSubtotal("Tổng chi phí lăn bánh",cashRollingCosts)}</div></article>
      <article class="payment-card loan" data-payment-panel="loan" ${paymentMode === "loan" ? "" : "hidden"}><span>THANH TOÁN VAY</span><h3>${money(loanTotal)}</h3><p>Trả trước cộng tổng chi phí lăn bánh, đã gồm bảo hiểm vật chất.</p><div class="fee-breakdown">${feeRow("Số tiền trả trước",downPayment,`${downPaymentPercentageText}% giá trị xe`)}${feeDivider("Chi phí lăn bánh")}${feeRow("Đăng ký biển",registration,registrationType === "city" ? "Thành phố" : "Tỉnh")}${feeRow("Phí dịch vụ đăng ký xe",registrationService)}${feeRow("Lệ phí đăng kiểm",inspection)}${feeRow("Bảo trì đường bộ",road,plate === "white" ? "Biển trắng" : "Biển vàng")}${feeRow("Bảo hiểm TNDS",liability,liabilityNote)}${feeRow("Bảo hiểm vật chất bắt buộc",physical,physicalInsurance.note)}${feeSubtotal("Tổng chi phí lăn bánh",loanRollingCosts)}</div><div class="loan-note"><span>Dư nợ dự kiến ${loanPercentageText}%</span><b>${money(remainingLoan)}</b><small>${remainingLoan ? "Chưa bao gồm lãi vay ngân hàng." : "Bạn đã nhập số tiền trả trước bằng toàn bộ giá trị xe."}</small>${remainingLoan ? `<a href="loan.html?amount=${Math.ceil(remainingLoan)}">Tính lãi và lịch trả góp <span>›</span></a>` : '<span class="loan-paid-off">Không còn dư nợ để tính lãi</span>'}</div></article></div>
      <p class="quote-disclaimer">Báo giá mang tính tham khảo theo dữ liệu hiện có. Chi phí thực tế có thể thay đổi theo thời điểm, địa phương, ngân hàng và chính sách bán hàng.${car.registrationNote ? ` ${esc(car.registrationNote)}` : ""}</p>`;
}
