import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CarSummary, CarSources } from "../js/detail-content.js";

const data = JSON.parse(readFileSync(new URL("../data/cars.json", import.meta.url), "utf8"));
const promotions = JSON.parse(readFileSync(new URL("../data/promotions.json", import.meta.url), "utf8"));
assert.equal(data.cars.length, 13);
assert.equal(new Set(data.cars.map(car => car.slug)).size, 13);
for (const car of data.cars) {
  assert.equal(car.price, Math.min(...car.versions.map(version => version.price)), car.slug);
  assert.ok(car.summary.description && car.summary.audience && car.summary.charging, car.slug);
  assert.equal(car.summary.highlights.length, 3, car.slug);
  assert.ok(car.sources.length > 0 && car.sources.every(source => new URL(source.url).protocol === "https:"), car.slug);
  assert.ok(CarSummary(car).includes('id="overview"'), car.slug);
  assert.ok(CarSummary(car).includes("Dung lượng pin"), car.slug);
  assert.ok(CarSummary(car).includes("Kích thước D × R × C"), car.slug);
  assert.ok(CarSummary(car).includes("Khoang hành lý / hàng"), car.slug);
  assert.ok(CarSummary(car).includes(car.specs.battery), car.slug);
  assert.ok(CarSummary(car).includes(car.specs.dimensions), car.slug);
  assert.ok(CarSources(car).includes(car.specsUpdated), car.slug);
}
const bySlug = slug => data.cars.find(car => car.slug === slug);
assert.match(bySlug("ec-van").specs.range, /175/);
assert.match(bySlug("ec-van").specs.battery, /18,3/);
assert.match(bySlug("ec-van").specs.dcCharge, /24,2/);
assert.match(bySlug("ec-van").specsNote, /150/);
assert.match(bySlug("vf-2").specs.dcCharge, /34 phút/);
assert.equal(bySlug("vf-2").specs.trunk, undefined);
assert.equal(bySlug("vf-2").specs.acCharge, undefined);
assert.equal(bySlug("vf-2").specs.vehicleWarranty, "5 năm / 130.000 km");
assert.equal(bySlug("vf-2").specs.batteryWarranty, "7 năm / 160.000 km");
assert.deepEqual(
  Object.entries(bySlug("vf-2").colorPrices).filter(([, price]) => price === 0).map(([color]) => color),
  ["Trắng Infinity Blanc", "Đỏ Solar Ruby", "Bạc Desat Silver"]
);
assert.equal(Object.values(bySlug("vf-2").colorPrices).filter(price => price === 8000000).length, 5);
assert.match(bySlug("vf-2").colorNote, /màu cơ bản/);
assert.match(CarSummary(bySlug("vf-2")), /Chưa có số liệu hãng công bố/);
assert.match(CarSummary(bySlug("ec-van")), /2\.600 lít/);
assert.match(CarSummary(bySlug("ec-van")), /1\.450 × 1\.470 × 1\.220 mm/);
assert.match(bySlug("vf-7").specs.battery, /70 kWh/);
assert.match(bySlug("vf-7").specsNote, /75,3/);
const vf7SteelFwd = bySlug("vf-7").versions.find(version => version.name === "Plus trần thép - Tiêu chuẩn 2");
const vf7SteelAwd = bySlug("vf-7").versions.find(version => version.name === "Plus trần thép - Tiêu chuẩn 2 · 2 cầu AWD");
const vf7GlassFwd = bySlug("vf-7").versions.find(version => version.name === "Plus trần kính - Tiêu chuẩn 2");
const vf7GlassAwd = bySlug("vf-7").versions.find(version => version.name === "Plus trần kính - Tiêu chuẩn 2 · 2 cầu AWD");
assert.equal(vf7SteelAwd.price - vf7SteelFwd.price, 49000000);
assert.equal(vf7GlassAwd.price - vf7GlassFwd.price, 49000000);
assert.match(bySlug("vf-7").specs.paidOptions, /49 triệu/);
assert.match(bySlug("mpv-7").specs.parkingSupport, /Camera lùi/);
assert.match(bySlug("vf-8-moi").specs.vehicleWarranty, /7 năm/);
assert.match(bySlug("vf-8").specs.vehicleWarranty, /10 năm/);
const vfWild = bySlug("vf-wild-comfort");
assert.equal(vfWild.price, 860000000);
assert.equal(vfWild.offer.price, 799000000);
assert.equal(vfWild.offer.discount, 61000000);
assert.equal(vfWild.powertrain, "REEV");
assert.match(vfWild.specs.range, /250 km/);
assert.match(vfWild.specs.combinedRange, /1\.000 km/);
assert.equal(vfWild.specs.battery, "46,4 kWh");
assert.equal(vfWild.specs.dimensions, "5.376 × 2.069 × 1.873 mm");
assert.equal(vfWild.specs.vehicleWarranty, "6 năm / 150.000 km");
assert.equal(vfWild.specs.batteryWarranty, "8 năm / 160.000 km");
assert.equal(vfWild.specs.trunk, undefined);
const vfWildPromotion = promotions.quoteOptions.model.find(item => item.carSlugs.includes("vf-wild-comfort"));
assert.equal(vfWildPromotion.value, 61000000);
assert.equal(vfWild.price - vfWildPromotion.value, 799000000);
const unsafe = { ...bySlug("vf-3"), name: '<img src=x onerror="alert(1)">', sources: [{ title: "Unsafe", url: "javascript:alert(1)" }] };
assert.ok(!CarSummary(unsafe).includes("<img src=x"));
assert.ok(!CarSources(unsafe).includes("javascript:"));
console.log("PASS: 13 model records, VF Wild Comfort data, sourced corrections, summaries, warranties and HTML escaping.");
